enableEntitiesDrop: true
enableBlocksDrop: false
notiUpdate: false
shiftToPickUp: false
actionBarMessage: false
minimumCmdDrop: 100
spawnerPercent: 100
defaultFortuneBonus: 0
defaultLootingBonus: 0
decimalPlace: 0
collateRadius: 3
chatMessage: true
chatAnnounce:
  monster: false
  animal: false
  player: true
  block: false
  commandDropped: true
particle:
  enable: true
  type: BLOCK_CRACK
  amount: 15
  data: redstone
particleSpawn:
  monster: false
  animal: true
  player: true
  block: false
  commandDropped: true
sound:
  enable: true
  type: BLOCK_NOTE_PLING
  volumn: 2.0
  pitch: 3.0
soundAnnounce:
  monster: false
  animal: true
  player: true
  block: false
  commandDropped: true
scheduleMode:
  enable: false
  radius: 2
  interval: 5
dropBlock:
  silkTouch: false
  creative: false
limit:
  enable: false
  time: 86400000
  amount: 20000
item:
  small:
    type: GOLD_NUGGET
    amount: 800
  normal:
    type: GOLD_INGOT
    amount: 1500
  big:
    type: GOLD_BLOCK
    amount: 2000
disableWorld:
- plot_world
