name: PickupMoney
main: com.gmail.vkhanh234.PickupMoney.PickupMoney
author: KickVN
version: 2.5.2
softdepend: [MythicMobs]
depend: [Vault]
commands:
   pickupmoney:
      description: Show PickupMoney's Command.
      usage: /pum
      aliases: [pum, pmoney]
permissions:
    PickupMoney.command:
        description: Allows you to use normal command.
        default: op
    PickupMoney.admincmd:
        description: Allows you to use admin's command.
        default: op
    PickupMoney.pickup:
        description: Allows you to pick up money.
        default: true
    PickupMoney.nolimit:
        description: No limited money.
        default: true